apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rcontroller
  labels:
    app: myapp
    type: fromt-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: fromt-end
    spec:
      containers:
       - name: redis
         image: redis
replicas: 3